// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
// import { useState, useEffect } from "react";
import { usePathname } from "next/navigation";
// const inter = Inter({ subsets: ["latin"] });
import Loader from "./components/loader";
import NavBar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Sushant Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const isHome = pathname === "/";
  // const [isLoading, setIsLoading] = useState(isHome);
  // const [isLoading, setIsLoading] = useState(false);

  // Sets target="_blank" rel="noopener noreferrer" on external links
  // const handleExternalLinks = () => {
  //   const allLinks = Array.from(document.querySelectorAll("a"));
  //   if (allLinks.length > 0) {
  //     allLinks.forEach((link) => {
  //       if (link.host !== window.location.host) {
  //         link.setAttribute("rel", "noopener noreferrer");
  //         link.setAttribute("target", "_blank");
  //       }
  //     });
  //   }
  // };

  // useEffect(() => {
  //   if (isLoading) {
  //     return;
  //   }

  //   if (location.hash) {
  //     const id = location.hash.substring(1); // location.hash without the '#'
  //     setTimeout(() => {
  //       const el = document.getElementById(id);
  //       if (el) {
  //         el.scrollIntoView();
  //         el.focus();
  //       }
  //     }, 0);
  //   }

  //   handleExternalLinks();
  // }, [isLoading]);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={inter.className}
        className="bg-[#121212]"
      >
        <Providers>
          {/* {children} */}
          {/* <Loader finishLoading={() => setIsLoading(false)} /> */}
          {/* {isLoading && isHome ? (
            <Loader finishLoading={() => setIsLoading(false)} />
          ) : (
            <div>
              <div id="content">{children}</div>
            </div>
          )} */}
          <div className="flex flex-col min-h-screen	">
            <NavBar />
            <div id="content">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
